import asyncio
import logging
import os
import src.config
from src.infrastructure.apis.youtube_api import YouTubeAPI

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

async def debug_upload():
    entity_id = "default_user"
    youtube_api = YouTubeAPI(entity_id=entity_id)
    
    # Use the sample video generated by test_processing.py
    video_path = os.path.abspath("sample.mp4")
    
    if not os.path.exists(video_path):
        print(f"Error: {video_path} does not exist. Run test_processing.py first.")
        return

    print(f"Attempting to upload {video_path}...")
    
    try:
        result = await youtube_api.upload_short(
            video_file_path=video_path,
            title="Test Short Video #Shorts",
            description="This is a test video uploaded via debug script. #Shorts",
            privacy_status="private", # Upload as private for testing
            preprocess=True
        )
        
        print("\nUpload Result:")
        print(result)
        
    except Exception as e:
        print(f"\nUpload Failed with Exception: {e}")

if __name__ == "__main__":
    asyncio.run(debug_upload())
