import { useQuery } from "@tanstack/react-query";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  BarChart3,
  CheckCircle2,
  XCircle,
  Clock,
  Send,
  Loader2,
  Sparkles,
  Video,
  Share2,
  Youtube,
  Instagram,
  Facebook,
  Info,
  TrendingUp,
  Calendar,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { apiGet } from "@/lib/api";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { motion } from "framer-motion";
import { PageHero } from "@/components/studio";

const CMS_BACKEND_URL =
  import.meta.env.VITE_CMS_BACKEND_URL || "http://127.0.0.1:8000";

interface StatusSummary {
  total_recipes: number;
  content_generated: number;
  pending_generation: number;
  completion_percentage: number;
  by_status: {
    not_generated: number;
    generated: number;
    pending: number;
    posted: number;
    declined?: number;
  };
}

interface ClipStats {
  total_projects: number;
  total_generated_clips: number;
  total_posted_clips: number;
  by_platform: Record<string, number>;
  project_status: {
    processing: number;
    completed: number;
    failed: number;
  };
}

export default function WPRMStats() {
  const { toast } = useToast();

  const { data: recipeStats, isLoading: recipesLoading } = useQuery({
    queryKey: ["wprm-stats"],
    queryFn: () => apiGet("/api/content/wprm-status-summary"),
    staleTime: 300000,
    refetchInterval: 30000,
  });

  const { data: clipStats, isLoading: clipsLoading } = useQuery({
    queryKey: ["clip-stats"],
    queryFn: () => apiGet("/api/clips/stats"),
    staleTime: 60000,
    refetchInterval: 30000,
  });

  // Default stats
  const defaultRecipeStats: StatusSummary = {
    total_recipes: 0,
    content_generated: 0,
    pending_generation: 0,
    completion_percentage: 0,
    by_status: { not_generated: 0, generated: 0, pending: 0, posted: 0 },
  };

  const defaultClipStats: ClipStats = {
    total_projects: 0,
    total_generated_clips: 0,
    total_posted_clips: 0,
    by_platform: {},
    project_status: { processing: 0, completed: 0, failed: 0 },
  };

  const currentStats = recipeStats || defaultRecipeStats;
  const currentClipStats = clipStats || defaultClipStats;

  const statCards = [
    {
      title: "Total Recipes",
      value: currentStats.total_recipes,
      icon: BarChart3,
      color: "text-white",
      bgColor: "bg-[#7C3AED]",
      description: "The complete library of recipes imported from WPRM.",
      tooltip:
        "This counts every single recipe card currently in your database.",
    },
    {
      title: "Videos Generated",
      value: currentClipStats.total_generated_clips,
      icon: Video,
      color: "text-white",
      bgColor: "bg-[#E11D48]",
      description: "Short-form clips created by AI from your long videos.",
      tooltip:
        "Total number of successful video clips generated by Opus Clips or Vizard.",
    },
    {
      title: "Content Posted",
      value:
        (currentStats.by_status?.posted || 0) +
        currentClipStats.total_posted_clips,
      icon: Send,
      color: "text-white",
      bgColor: "bg-[#16A34A]",
      description: "Recipes and Clips successfully published to platforms.",
      tooltip:
        "Combined count of recipes updated on WordPress and clips posted to Social Media.",
    },
    {
      title: "Completion Rate",
      value: `${currentStats.completion_percentage.toFixed(1)}%`,
      icon: TrendingUp,
      color: "text-white",
      bgColor: "bg-[#F59E0B]",
      description: "Percentage of recipes with fully generated AI content.",
      tooltip:
        "Tracks how many recipes have moved through the entire AI generation workflow.",
    },
  ];

  if (recipesLoading || clipsLoading) {
    return (
      <div className="flex flex-col items-center justify-center h-[60vh]">
        <Loader2 className="h-10 w-10 animate-spin text-[#A9542F] mb-4" />
        <p className="text-muted-foreground font-medium">
          Gathering performance metrics...
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-in fade-in duration-500 pb-8">
      <PageHero
        eyebrow="Analytics"
        title="Performance Analytics"
        subtitle="Track the heartbeat of your content operations — AI generation efficiency, publishing velocity, and channel activity."
        icon={BarChart3}
      />

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {statCards.map((stat, index) => (
          <motion.div
            key={stat.title}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
          >
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Card className="border-none shadow-lg hover:shadow-2xl transition-all duration-300 bg-card group cursor-default h-full">
                    <CardContent className="p-6 flex flex-col justify-between h-full">
                      <div className="flex justify-between items-start mb-4">
                        <div
                          className={`p-3 rounded-2xl ${stat.bgColor} transition-transform group-hover:scale-110 duration-300`}
                        >
                          <stat.icon className={`h-6 w-6 ${stat.color}`} />
                        </div>
                        <Info className="h-4 w-4 text-muted-foreground/50 hover:text-muted-foreground transition-colors" />
                      </div>
                      <div>
                        <h3 className="text-3xl font-extrabold text-foreground tracking-tight mb-1">
                          {stat.value}
                        </h3>
                        <p className="font-semibold text-muted-foreground mb-1">
                          {stat.title}
                        </p>
                        <p className="text-xs text-muted-foreground font-medium leading-relaxed">
                          {stat.description}
                        </p>
                      </div>
                    </CardContent>
                  </Card>
                </TooltipTrigger>
                <TooltipContent
                  side="bottom"
                  className="max-w-xs bg-[hsl(var(--olive-dark))] text-white border-none p-3 shadow-xl"
                >
                  {stat.tooltip}
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </motion.div>
        ))}
      </div>

      {/* Main Content Tabs */}
      <Tabs defaultValue="recipes" className="space-y-8">
        <TabsList className="bg-card/50 backdrop-blur-md p-1 rounded-2xl border border-border shadow-sm w-full max-w-md mx-auto grid grid-cols-2 h-14">
          <TabsTrigger
            value="recipes"
            className="rounded-xl data-[state=active]:bg-card data-[state=active]:text-[#8A3F26] data-[state=active]:shadow-md font-semibold text-muted-foreground transition-all"
          >
            <div className="flex items-center gap-2">
              <Clock className="w-4 h-4" />
              Recipe Production
            </div>
          </TabsTrigger>
          <TabsTrigger
            value="clips"
            className="rounded-xl data-[state=active]:bg-card data-[state=active]:text-[#8A3F26] data-[state=active]:shadow-md font-semibold text-muted-foreground transition-all"
          >
            <div className="flex items-center gap-2">
              <Video className="w-4 h-4" />
              Video Distribution
            </div>
          </TabsTrigger>
        </TabsList>

        <TabsContent
          value="recipes"
          className="animate-in slide-in-from-bottom-5 duration-500"
        >
          <Card className="border-none shadow-xl bg-card/80 backdrop-blur-xl overflow-hidden ring-1 border-border">
            <CardHeader className="bg-gradient-to-b from-muted/40 to-white border-b border-border p-8">
              <CardTitle className="text-2xl font-bold text-foreground flex items-center gap-3">
                <Sparkles className="h-6 w-6 text-yellow-500" />
                Recipe Content Pipeline
              </CardTitle>
              <CardDescription className="text-base text-muted-foreground">
                Visualizing the journey of your recipes from raw WPRM imports to
                fully published content.
              </CardDescription>
            </CardHeader>
            <CardContent className="p-8">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
                <div className="space-y-8">
                  {/* Status Item: Not Generated */}
                  <div className="group bg-muted/40 rounded-2xl p-6 hover:bg-card hover:shadow-lg hover:ring-1 hover:ring-yellow-400/30 transition-all duration-300">
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-3">
                        <div className="h-2 w-2 rounded-full bg-yellow-400 shadow-[0_0_10px_rgba(250,204,21,0.5)]" />
                        <span className="font-bold text-muted-foreground">
                          Not Generated
                        </span>
                      </div>
                      <Badge
                        variant="outline"
                        className="bg-yellow-50 text-yellow-700 border-yellow-200"
                      >
                        {currentStats.by_status?.not_generated || 0} recipes
                      </Badge>
                    </div>
                    <p className="text-xs text-muted-foreground mb-4 pl-5">
                      New recipes imported from WordPress that haven't been
                      processed by AI yet.
                    </p>
                    <div className="w-full bg-muted/50 rounded-full h-2.5 overflow-hidden">
                      <div
                        className="bg-yellow-400 h-2.5 rounded-full transition-all duration-1000 ease-out group-hover:bg-yellow-500"
                        style={{
                          width: `${currentStats.total_recipes > 0 ? ((currentStats.by_status?.not_generated || 0) / currentStats.total_recipes) * 100 : 0}%`,
                        }}
                      />
                    </div>
                  </div>

                  {/* Status Item: Awaiting Review */}
                  <div className="group bg-muted/40 rounded-2xl p-6 hover:bg-card hover:shadow-lg hover:ring-1 hover:ring-blue-400/30 transition-all duration-300">
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-3">
                        <div className="h-2 w-2 rounded-full bg-blue-500 shadow-[0_0_10px_rgba(59,130,246,0.5)]" />
                        <span className="font-bold text-muted-foreground">
                          Awaiting Review
                        </span>
                      </div>
                      <Badge
                        variant="outline"
                        className="bg-blue-50 text-blue-700 border-blue-200"
                      >
                        {currentStats.by_status?.generated || 0} recipes
                      </Badge>
                    </div>
                    <p className="text-xs text-muted-foreground mb-4 pl-5">
                      AI has generated content, but it needs your approval in
                      the <strong>Review</strong> tab.
                    </p>
                    <div className="w-full bg-muted/50 rounded-full h-2.5 overflow-hidden">
                      <div
                        className="bg-blue-500 h-2.5 rounded-full transition-all duration-1000 ease-out group-hover:bg-blue-600"
                        style={{
                          width: `${currentStats.total_recipes > 0 ? ((currentStats.by_status?.generated || 0) / currentStats.total_recipes) * 100 : 0}%`,
                        }}
                      />
                    </div>
                  </div>
                </div>

                <div className="space-y-8">
                  {/* Status Item: Ready to Post */}
                  <div className="group bg-muted/40 rounded-2xl p-6 hover:bg-card hover:shadow-lg hover:ring-1 hover:ring-green-400/30 transition-all duration-300">
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-3">
                        <div className="h-2 w-2 rounded-full bg-green-500 shadow-[0_0_10px_rgba(34,197,94,0.5)]" />
                        <span className="font-bold text-muted-foreground">
                          Ready to Post
                        </span>
                      </div>
                      <Badge
                        variant="outline"
                        className="bg-green-50 text-green-700 border-green-200"
                      >
                        {currentStats.by_status?.pending || 0} recipes
                      </Badge>
                    </div>
                    <p className="text-xs text-muted-foreground mb-4 pl-5">
                      Approved recipes waiting in the queue to be synced back to
                      WordPress.
                    </p>
                    <div className="w-full bg-muted/50 rounded-full h-2.5 overflow-hidden">
                      <div
                        className="bg-green-500 h-2.5 rounded-full transition-all duration-1000 ease-out group-hover:bg-green-600"
                        style={{
                          width: `${currentStats.total_recipes > 0 ? ((currentStats.by_status?.pending || 0) / currentStats.total_recipes) * 100 : 0}%`,
                        }}
                      />
                    </div>
                  </div>

                  {/* Status Item: Posted */}
                  <div className="group bg-muted/40 rounded-2xl p-6 hover:bg-card hover:shadow-lg hover:ring-1 hover:ring-[#C46B4A]/30 transition-all duration-300">
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-3">
                        <div className="h-2 w-2 rounded-full bg-[#A9542F] shadow-[0_0_10px_rgba(147,51,234,0.5)]" />
                        <span className="font-bold text-muted-foreground">
                          Published
                        </span>
                      </div>
                      <Badge
                        variant="outline"
                        className="bg-[#FBF1EA] text-[#8A3F26] border-[#E8C4B2]"
                      >
                        {currentStats.by_status?.posted || 0} recipes
                      </Badge>
                    </div>
                    <p className="text-xs text-muted-foreground mb-4 pl-5">
                      Finalized content successfully updated on your live
                      WordPress site.
                    </p>
                    <div className="w-full bg-muted/50 rounded-full h-2.5 overflow-hidden">
                      <div
                        className="bg-[#A9542F] h-2.5 rounded-full transition-all duration-1000 ease-out group-hover:bg-[#8A3F26]"
                        style={{
                          width: `${currentStats.total_recipes > 0 ? ((currentStats.by_status?.posted || 0) / currentStats.total_recipes) * 100 : 0}%`,
                        }}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent
          value="clips"
          className="animate-in slide-in-from-bottom-5 duration-500 space-y-6"
        >
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Generation Status */}
            <Card className="border-none shadow-xl bg-card/80 backdrop-blur-xl ring-1 border-border h-full">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Video className="w-5 h-5 text-[hsl(var(--terracotta-dark))]" />
                  Processing Pipeline
                </CardTitle>
                <CardDescription>
                  Status of your video repurposing jobs
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="bg-blue-50/50 rounded-xl p-4 flex justify-between items-center group hover:bg-blue-50 transition-colors">
                  <div className="flex items-center gap-4">
                    <div className="h-10 w-10 bg-blue-100 rounded-full flex items-center justify-center text-blue-600">
                      <Loader2 className="w-5 h-5 animate-spin" />
                    </div>
                    <div>
                      <p className="font-bold text-foreground">Processing</p>
                      <p className="text-xs text-muted-foreground">
                        Currently being generated
                      </p>
                    </div>
                  </div>
                  <span className="text-2xl font-bold text-blue-700">
                    {currentClipStats.project_status.processing}
                  </span>
                </div>

                <div className="bg-[#FBF1EA]/50 rounded-xl p-4 flex justify-between items-center group hover:bg-[#FBF1EA] transition-colors">
                  <div className="flex items-center gap-4">
                    <div className="h-10 w-10 bg-[#F3DECF] rounded-full flex items-center justify-center text-[#A9542F]">
                      <Send className="w-5 h-5" />
                    </div>
                    <div>
                      <p className="font-bold text-foreground">Distributed</p>
                      <p className="text-xs text-muted-foreground">
                        Posted to social platforms
                      </p>
                    </div>
                  </div>
                  <span className="text-2xl font-bold text-[#8A3F26]">
                    {currentClipStats.total_posted_clips}
                  </span>
                </div>

                <div className="bg-green-50/50 rounded-xl p-4 flex justify-between items-center group hover:bg-green-50 transition-colors">
                  <div className="flex items-center gap-4">
                    <div className="h-10 w-10 bg-green-100 rounded-full flex items-center justify-center text-green-600">
                      <CheckCircle2 className="w-5 h-5" />
                    </div>
                    <div>
                      <p className="font-bold text-foreground">Completed</p>
                      <p className="text-xs text-muted-foreground">
                        Ready for review/download
                      </p>
                    </div>
                  </div>
                  <span className="text-2xl font-bold text-green-700">
                    {currentClipStats.project_status.completed}
                  </span>
                </div>
              </CardContent>
            </Card>

            {/* Platform Breakdown */}
            <Card className="border-none shadow-xl bg-card/80 backdrop-blur-xl ring-1 border-border h-full">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Share2 className="w-5 h-5 text-pink-600" />
                  Platform Reach
                </CardTitle>
                <CardDescription>
                  Where your video content is living right now
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {Object.entries(currentClipStats.by_platform).length > 0 ? (
                  Object.entries(currentClipStats.by_platform).map(
                    ([platform, count]) => (
                      <div
                        key={platform}
                        className="flex items-center justify-between p-4 rounded-xl bg-card border border-border shadow-sm hover:shadow-md transition-shadow"
                      >
                        <div className="flex items-center gap-4">
                          {platform.toLowerCase().includes("youtube") ? (
                            <div className="h-10 w-10 bg-red-50 rounded-full flex items-center justify-center">
                              <Youtube className="w-6 h-6 text-red-600" />
                            </div>
                          ) : platform.toLowerCase().includes("instagram") ? (
                            <div className="h-10 w-10 bg-pink-50 rounded-full flex items-center justify-center">
                              <Instagram className="w-6 h-6 text-pink-600" />
                            </div>
                          ) : (
                            <div className="h-10 w-10 bg-blue-50 rounded-full flex items-center justify-center">
                              <Facebook className="w-6 h-6 text-blue-600" />
                            </div>
                          )}
                          <div>
                            <span className="font-bold text-foreground capitalize block">
                              {platform.replace(/_/g, " ")}
                            </span>
                            <span className="text-xs text-muted-foreground">
                              Total clips
                            </span>
                          </div>
                        </div>
                        <Badge
                          variant="secondary"
                          className="px-3 py-1 text-sm bg-muted text-muted-foreground"
                        >
                          {count}
                        </Badge>
                      </div>
                    ),
                  )
                ) : (
                  <div className="flex flex-col items-center justify-center h-48 text-center bg-muted/40/50 rounded-2xl">
                    <Video className="h-8 w-8 text-muted-foreground/50 mb-2" />
                    <p className="font-medium text-muted-foreground">
                      No clips posted yet
                    </p>
                    <p className="text-xs text-muted-foreground max-w-xs mt-1">
                      Once you distribute clips to social media, stats will
                      appear here.
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
