# src/domain/models/clip_model.py

from sqlmodel import SQLModel, Field, Relationship, Column, Text
from typing import Optional, List
from datetime import datetime
from enum import Enum


class ClipStatus(str, Enum):
    """Status of a generated clip"""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    POSTED = "posted"


class SocialPlatform(str, Enum):
    """Supported social media platforms"""
    YOUTUBE_SHORTS = "youtube_shorts"
    TIKTOK = "tiktok"
    INSTAGRAM_REELS = "instagram_reels"
    FACEBOOK_REELS = "facebook_reels"
    LINKEDIN = "linkedin"
    TWITTER = "twitter"


class VideoClip(SQLModel, table=True):
    """
    Represents a video clip generated by Vizard AI
    """
    __tablename__ = "video_clips"
    
    id: Optional[int] = Field(default=None, primary_key=True)
    
    # Vizard project info
    vizard_project_id: str = Field(index=True)
    clip_url: Optional[str] = Field(default=None, sa_column=Column(Text))
    thumbnail_url: Optional[str] = Field(default=None, sa_column=Column(Text))
    
    # Source video info
    source_video_url: str
    source_platform: str  # youtube, tiktok, vimeo, etc.
    
    # Clip metadata
    title: Optional[str] = None
    description: Optional[str] = None
    duration: Optional[int] = None  # in seconds
    keywords: Optional[str] = None
    
    # Target platforms (JSON array stored as string)
    target_platforms: str = Field(default="[]")  # ["youtube_shorts", "tiktok", etc.]
    
    # Status tracking
    status: ClipStatus = Field(default=ClipStatus.PENDING)
    
    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    approved_at: Optional[datetime] = None
    rejected_at: Optional[datetime] = None
    
    # User who approved/rejected
    approved_by: Optional[int] = None
    rejection_reason: Optional[str] = None
    
    # Relationships
    social_posts: List["SocialPost"] = Relationship(back_populates="clip")


class SocialPost(SQLModel, table=True):
    """
    Represents a post to a specific social media platform
    """
    __tablename__ = "social_posts"
    
    id: Optional[int] = Field(default=None, primary_key=True)
    
    # Related clip
    clip_id: int = Field(foreign_key="video_clips.id")
    clip: Optional[VideoClip] = Relationship(back_populates="social_posts")
    
    # Platform info
    platform: SocialPlatform
    
    # Post content
    caption: Optional[str] = None
    hashtags: Optional[str] = None
    
    # Post status
    is_posted: bool = Field(default=False)
    post_url: Optional[str] = None
    platform_post_id: Optional[str] = None
    
    # Error tracking
    error_message: Optional[str] = None
    retry_count: int = Field(default=0)
    
    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    posted_at: Optional[datetime] = None
    
    # Scheduling
    scheduled_for: Optional[datetime] = None


class VizardProject(SQLModel, table=True):
    """
    Represents a Vizard AI project for tracking
    """
    __tablename__ = "vizard_projects"
    
    id: Optional[int] = Field(default=None, primary_key=True)
    
    # Vizard info
    project_id: str = Field(unique=True, index=True)
    project_name: str
    
    # Source video
    source_video_url: str
    source_platform: str
    
    # Target platform
    target_platform: str = Field(default="unknown")
    
    # Configuration
    language: str = Field(default="en")
    max_clips: int = Field(default=5)
    keywords: Optional[str] = None
    
    # Status
    is_processed: bool = Field(default=False)
    clips_generated: int = Field(default=0)
    
    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    processed_at: Optional[datetime] = None
    
    # Error tracking
    error_message: Optional[str] = None
